### ISSUE TITLE
Seemingly random test failures

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#11]
Getting ready for the next release, trying to package up the latest changes for Alpine to make sure I'm good to go once you release it. I seem to be getting semi-random test failures. Sometimes the tests will fail, and others they'll work just fine:

All the failures look like this:

```
_________________________________ test_main[3] _________________________________

tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_3_0')
name = 'remedy', args = 'home@❬HOST❭~❬USER❭', env = {}
stdout = 'home@❬HOST❭~❬USER❭: 4.15 GiB', stderr = '^$', status = 0

    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)

tests/test_cli.py:94:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_cli.py:83: in check_command
    Matches(stderr, flags=re.DOTALL).assert_matches(process.stderr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Matches('^$', flags=regex.S | regex.V0)
    # regex failed to match at:
    #
    #> Traceback (most recent call last)...name
    #>     raise Invalid(f"{arg}: expected a name")
    #> voluptuous.error.Invalid: 6f24e76175ac: expected a name
s = 'Traceback (most recent call last):\n  File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2....03, in a_name\n    raise Invalid(f"{arg}: expected a name")\nvoluptuous.error.Invalid: 6f24e76175ac: expected a name\n'

    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E
E       > Traceback (most recent call last):
E         ^
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/config.py", line 154, in get_repos
E       >     children = repositories[spec]
E       >                ~~~~~~~~~~~~^^^^^^
E       > KeyError: 'home@6f24e76175ac~buildozer'
E       >
E       > During handling of the above exception, another exception occurred:
E       >
E       > Traceback (most recent call last):
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/./bs", line 5, in <module>
E       >     main()
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/main.py", line 332, in main
E       >     repos = collect_repos(requests, cmdline['--record'])
E       >             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/main.py", line 64, in collect_repos
E       >     new_repos = get_repos(request)
E       >                 ^^^^^^^^^^^^^^^^^^
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/config.py", line 158, in get_repos
E       >     children = [Repository(spec)]
E       >                 ^^^^^^^^^^^^^^^^
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/config.py", line 69, in __init__
E       >     self.host = a_name(host) or hostname
E       >                 ^^^^^^^^^^^^
E       >   File "/home/andy/alpine-packaging/aports/community/borg-space/src/borg-space-2.1/borg_space/config.py", line 203, in a_name
E       >     raise Invalid(f"{arg}: expected a name")
E       > voluptuous.error.Invalid: 6f24e76175ac: expected a name

/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: remedy
```

**Comment by adhawkins** [comment]
Getting some other failures when running in the Alpine build pipelines. For example:

```
________________________________ test_main[42] _________________________________
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_42_0')
name = 'islander', args = 'all', env = {}
stdout = "bs warning: home@❬HOST❭~❬USER❭, 'size': not available.\nwork@❬HOST❭~❬USER❭: 1.83 GiB"
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("bs warning: home@runner-x2y6gj3b-project-1075-concurrent-1~buildozer, 'size': not available.\nwork@runner-x2y...                  ^
    #>     not available.
    #> work@runner-x2y6gj3b-project-1075-concurrent-1~buildozer: 1.83 GiB
s = "bs warning: home@runner-x2y6gj3b-project-1075-concurrent-1~buildozer, 'size':\n    not available.\nwork@runner-x2y6gj3b-project-1075-concurrent-1~buildozer: 1.83 GiB\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > bs warning: home@runner-x2y6gj3b-project-1075-concurrent-1~buildozer, 'size':
E                                                                                      ^
E       >     not available.
E       > work@runner-x2y6gj3b-project-1075-concurrent-1~buildozer: 1.83 GiB
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
```

I've attached a log file of the full output

[test-log.txt](https://github.com/KenKundert/borg-space/files/11712191/test-log.txt)

**Comment by KenKundert** [comment]
Oh, it is probably because the hostname starts with a digit.  I had read somewhere that hostnames must start with a letter, but maybe that is no longer a constraint.

I will loosen the constraint.

**Comment by KenKundert** [comment]
I have upgraded the github version.  Can you run your tests on the new version.

**Comment by nekopsykose** [comment]
seems to still fail

```
=================================== FAILURES ===================================
________________________________ test_main[44] _________________________________
[gw43] linux -- Python 3.11.4 /builds/alpine/aports/community/borg-space/src/borg-space-2.1/.testenv/bin/python3
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/popen-gw43/test_main_44_0')
name = 'combat', args = 'all', env = {}
stdout = "HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning: home@❬HOST❭~❬USER❭, 'size': not available.\n❬HOST❭\\s+❬USER❭\\s+work     1.83 GiB  Sun, Jun 04"
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning: home@runner-x2y6gj3b-project-1-concurrent-0~bu...     ^
    #>     not available.
    #> runner-x2y6gj3b-project-1-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04
s = "HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning: home@runner-x2y6gj3b-project-1-concurrent-0~buildozer, 'size':\n    not available.\nrunner-x2y6gj3b-project-1-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > HOST     USER     CONFIG   SIZE      LAST BACK UP
E       > bs warning: home@runner-x2y6gj3b-project-1-concurrent-0~buildozer, 'size':
E                                                                                   ^
E       >     not available.
E       > runner-x2y6gj3b-project-1-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: combat
```

**Comment by KenKundert** [comment]
Sorry about that.  I forgot about Andy's second post.  Should be fixed now on github.

**Comment by nekopsykose** [comment]
hmm, still seems to be the same (same error)

**Comment by adhawkins** [comment]
> hmm, still seems to be the same (same error)

Are you testing against the (presumably) unreleased changes on Github, or just re-running the Alpine CI? If the latter, it is specifically downloading the released version.

**Comment by adhawkins** [comment]
I've just applied those two test fix commits as patches, and still seeing failures:

```
============================= test session starts ==============================
platform linux -- Python 3.11.4, pytest-7.3.2, pluggy-1.0.0
rootdir: /builds/adhawkins/aports/community/borg-space/src/borg-space-2.1
plugins: pytest_tmp_files-0.0.1
collected 51 items
tests/test_cli.py .........................................FFFF......    [100%]
=================================== FAILURES ===================================
________________________________ test_main[42] _________________________________
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_42_0')
name = 'islander', args = 'all', env = {}
stdout = "bs warning:[\\s+]home@❬HOST❭~❬USER❭, 'size': not available.\nwork@❬HOST❭~❬USER❭: 1.83 GiB"
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("bs warning:[\\s+]home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size': not available.\nwork@runne...                  ^
    #>     not available.
    #> work@runner--gmdm8s8-project-1075-concurrent-0~buildozer: 1.83 GiB
s = "bs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':\n    not available.\nwork@runner--gmdm8s8-project-1075-concurrent-0~buildozer: 1.83 GiB\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > bs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
E                                                                                      ^
E       >     not available.
E       > work@runner--gmdm8s8-project-1075-concurrent-0~buildozer: 1.83 GiB
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: islander
________________________________ test_main[43] _________________________________
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_43_0')
name = 'plummy', args = 'all', env = {}
stdout = "home: 4.15 GiB.  Last back up: Fri, Jun 02.  Last squeeze: Sat, May 27.\nbs warning:[\\s+]work@❬HOST❭~❬USER❭, 'size': not available."
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("home: 4.15 GiB.  Last back up: Fri, Jun 02.  Last squeeze: Sat, May 27.\nbs warning:[\\s+]work@runner--gmdm8s...'size':
    #                                                                               ^
    #>     not available.
s = "home: 4.15 GiB.  Last back up: Fri, Jun 02.  Last squeeze: Sat, May 27.\nbs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':\n    not available.\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > home: 4.15 GiB.  Last back up: Fri, Jun 02.  Last squeeze: Sat, May 27.
E       > bs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
E                                                                                      ^
E       >     not available.
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: plummy
________________________________ test_main[44] _________________________________
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_44_0')
name = 'combat', args = 'all', env = {}
stdout = "HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning:[\\s+]home@❬HOST❭~❬USER❭, 'size': not available.\n❬HOST❭\\s+❬USER❭\\s+work     1.83 GiB  Sun, Jun 04"
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning:[\\s+]home@runner--gmdm8s8-project-1075-concurr...  ^
    #>     not available.
    #> runner--gmdm8s8-project-1075-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04
s = "HOST     USER     CONFIG   SIZE      LAST BACK UP\nbs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':\n    not available.\nrunner--gmdm8s8-project-1075-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > HOST     USER     CONFIG   SIZE      LAST BACK UP
E       > bs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
E                                                                                      ^
E       >     not available.
E       > runner--gmdm8s8-project-1075-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: combat
________________________________ test_main[45] _________________________________
tmp_files = TestPath('/tmp/pytest-of-buildozer/pytest-1/test_main_45_0')
name = 'envision', args = 'all', env = {}
stdout = "HOST     USER  CONFIG    SIZE     LAST BACK UP\n❬HOST❭\\s+❬USER❭\\s+home      4.15 GiB Fri, Jun 02\nbs warning:[\\s+]work@❬HOST❭~❬USER❭, 'size': not available."
stderr = '^$', status = 0
    @parametrize(
        schema = borg_space_schema,
        indirect = ['tmp_files'],
    )
    def test_main(tmp_files, name, args, env, stdout, stderr, status):
>       check_command(name, args, env, stdout, stderr, status, home=tmp_files)
tests/test_cli.py:95: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_cli.py:85: in check_command
    Matches(stdout, flags=re.DOTALL).assert_matches(process.stdout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Matches("HOST     USER  CONFIG    SIZE     LAST BACK UP\nrunner--gmdm8s8-project-1075-concurrent-0\\s+buildozer\\s+hom...'size':
    #                                                                               ^
    #>     not available.
s = "HOST     USER  CONFIG    SIZE     LAST BACK UP\nrunner--gmdm8s8-project-1075-concurrent-0 buildozer home      4.15 GiB Fri, Jun 02\nbs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':\n    not available.\n"
    def assert_matches(self, s: str) -> None:
>       assert self == s, self._fail
E       AssertionError:  regex failed to match at:
E       
E       > HOST     USER  CONFIG    SIZE     LAST BACK UP
E       > runner--gmdm8s8-project-1075-concurrent-0 buildozer home      4.15 GiB Fri, Jun 02
E       > bs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
E                                                                                      ^
E       >     not available.
/usr/lib/python3.11/site-packages/re_assert.py:63: AssertionError
----------------------------- Captured stdout call -----------------------------
Running: envision
=========================== short test summary info ============================
FAILED tests/test_cli.py::test_main[42] - AssertionError:  regex failed to match at:
> bs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
                                                                               ^
>     not available.
> work@runner--gmdm8s8-project-1075-concurrent-0~buildozer: 1.83 GiB
FAILED tests/test_cli.py::test_main[43] - AssertionError:  regex failed to match at:
> home: 4.15 GiB.  Last back up: Fri, Jun 02.  Last squeeze: Sat, May 27.
> bs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
                                                                               ^
>     not available.
FAILED tests/test_cli.py::test_main[44] - AssertionError:  regex failed to match at:
> HOST     USER     CONFIG   SIZE      LAST BACK UP
> bs warning: home@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
                                                                               ^
>     not available.
> runner--gmdm8s8-project-1075-concurrent-0 buildozer work     1.83 GiB  Sun, Jun 04
FAILED tests/test_cli.py::test_main[45] - AssertionError:  regex failed to match at:
> HOST     USER  CONFIG    SIZE     LAST BACK UP
> runner--gmdm8s8-project-1075-concurrent-0 buildozer home      4.15 GiB Fri, Jun 02
> bs warning: work@runner--gmdm8s8-project-1075-concurrent-0~buildozer, 'size':
                                                                               ^
>     not available.
======================== 4 failed, 47 passed in 29.69s =========================
>>> ERROR: borg-space: check failed
```

**Comment by nekopsykose** [comment]
> Are you testing against the (presumably) unreleased changes on Github, or just re-running the Alpine CI? If the latter, it is specifically downloading the released version.  

you're wrong, it was with the patches (i.e. applied to the release)

**Comment by KenKundert** [comment]
Once again, I apologize. I have managed to fully reproduce the problem and I believe I have resolved it.  The fix is up on github.

**Comment by nekopsykose** [comment]
no worries. and that works, thank you!

**Comment by KenKundert** [comment]
Great.  Thank you.  I really appreciate all of your efforts.  I think everything is resolved, so I will now do a formal release so the fixes are on PyPI.
